dockerd: update version checking mechanism
https://github.com/moby/moby/commit/a7a7c732c0dc02ee5b5515f4ca868ef50cafa4a1
changed package pinning from commit hash to version for some dependencies
(but not all, libnetwork is still referenced by commit)

Support the version-based pinning mechanism in addition to commit-based

Signed-off-by: Andy Dodd <atd7@cornell.edu>

diff --git a/utils/dockerd/Makefile b/utils/dockerd/Makefile
--- a/utils/dockerd/Makefile
+++ b/utils/dockerd/Makefile
@@ -66,12 +66,25 @@ define EnsureVendoredVersion
 	)
 endef
 
+# $(1) = path to dependent package 'Makefile'
+# $(2) = relevant dependency '.installer' file
+define EnsureVendoredCommit
+	( \
+		DEP_VER=$$$$( grep --only-matching --perl-regexp '(?<=PKG_SOURCE_VERSION:=)(.*)' "$(1)" ); \
+		VEN_VER=$$$$( grep --only-matching --perl-regexp '(?<=_COMMIT:=)(.*)(?=})' "$(PKG_BUILD_DIR)/hack/dockerfile/install/$(2)" ); \
+		if [ "$$$${VEN_VER}" != "$$$${DEP_VER}" ]; then \
+			echo "ERROR: Expected 'PKG_SOURCE_VERSION:=$$$${VEN_VER}' in '$(1)', found 'PKG_SOURCE_VERSION:=$$$${DEP_VER}'"; \
+			exit 1; \
+		fi \
+	)
+endef
+
 define Build/Prepare
 	$(Build/Prepare/Default)
 
 	# Verify dependencies are the vendored version
 	$(call EnsureVendoredVersion,../containerd/Makefile,containerd.installer)
-	$(call EnsureVendoredVersion,../libnetwork/Makefile,proxy.installer)
+	$(call EnsureVendoredCommit,../libnetwork/Makefile,proxy.installer)
 	$(call EnsureVendoredVersion,../runc/Makefile,runc.installer)
 	$(call EnsureVendoredVersion,../tini/Makefile,tini.installer)
 
